/// This file was generated by C# converter tool
/// Any changes made to this file manually will be lost next time the file is regenerated.

using System.Linq;
using TypeScript.CSharp;

namespace Bailey
{
    interface BrowserMessagesInfo
    {
        (String encKey, String macKey)bundle
        {
            get;
            set;
        }

        String harFilePath
        {
            get;
            set;
        }
    }

    interface WSMessage
    {
        dynamic type
        {
            get;
            set;
        }

        String data
        {
            get;
            set;
        }
    }
}