/// This file was generated by C# converter tool
/// Any changes made to this file manually will be lost next time the file is regenerated.

using System.Linq;
using TypeScript.CSharp;

namespace Bailey
{
    using NodeAttributes = Nullable<OrType<Dictionary<string, string>, string>>;
    using NodeData = Nullable<OrType<List<Node>, dynamic>>;
    using Node = List<object>;
}